name: Docker image build and push

on:
  push:
    branches:
      - main  # Triggers the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out the repository code

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
